# Generated by Django 2.2.1 on 2019-12-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWeb', '0002_auto_20191203_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='defenceinfo',
            name='defence',
            field=models.CharField(default='Project', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defenceinfo',
            name='year',
            field=models.CharField(default='2019', max_length=1000),
            preserve_default=False,
        ),
    ]
